queue_rules:
  - name: default
    queue_conditions:
      - "#approved-reviews-by>1"
      - base=main
      - label=automerge
    merge_conditions:
      - "#approved-reviews-by>1"
    commit_message_template: |
      {{ title }} (#{{ number }})
      {{ body }}
    merge_method: squash

pull_request_rules:
  - name: backport patches to main branch
    conditions:
      - label=backport/main
    actions:
      backport:
        branches:
          - main
  - name: backport patches to v0.17.x branch
    conditions:
      - base=main
      - label=backport/0.17.x
    actions:
      backport:
        branches:
          - release/v0.17.x
  - name: backport patches to v0.16.x branch
    conditions:
      - base=main
      - label=backport/0.16.x
    actions:
      backport:
        branches:
          - release/v0.16.x
  - name: automerge to main with label "automerge" and branch protection passing
    conditions: []
    actions:
      queue:
